# sudo apt-get install build-essential libssl-dev libffi-dev python-dev
# sudo apt install python3-pip
# If necessary, give permission to make changes in /usr/lib/python3/dist-packages
# sudo chmod 777 dist-packages
# pip3 install cryptography

#    return [key, encryptedMessage] [] brackets are most likely optional

from cryptography.fernet import Fernet

# Encrypting input
def encrypt(message):
# Key is generated by using the library
    key = Fernet.generate_key()
    cryptoKey = Fernet(key)
# Key gets encrypted in ASCII format
    encryptedMessage = cryptoKey.encrypt(message.encode('ascii'))
    return key, encryptedMessage

# Uses the encryped message as input and decrypts it
def decrypt(key, encryptedMessage):
    decryptoKey = Fernet(key)
    message = decryptoKey.decrypt(encryptedMessage)
    return message

cryptoKey = encrypt("This is supposed to be a secret")
print(cryptoKey[0]) # First key
print(cryptoKey[1]) # Second key
# Both keys are needed to decrypt the message
print(decrypt(cryptoKey[0], cryptoKey[1]))
